# Generated by Django 6.1 on 2026-08-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_created_at_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='theme_preference',
            field=models.CharField(default='light', max_length=10),
        ),
    ]
